<?php
$lang = [
    '855 FOREX' => '855  ฟอเร็กซ์',
    'Account Balance' => 'ยอดเงิน',
    'Amount' => 'จำนวนเงิน',
    'Bet List' => 'รายการเดิมพัน',
    'Bet Records' => 'ประวัติเดิมพัน',
    'Bet time' => 'เวลาเดิมพัน',
    'Discount' => 'ส่วนลด',
    'Game' => 'เกมส์',
    'Game ID' => 'ไอดีเกมส์',
    'Last Bonus' => 'โบนัสล่าสุด',
    'Member Center' => 'ศุนย์สมาชิก',
    'No' => 'ลำดับ',
    'No record found!' => 'ไม่พบบันทึก!',
    'Number' => 'จำนวน',
    'Pool' => 'พูล',
    'Rate' => 'อัตรา',
    'Sports 2' => 'สปอร์ต 2',
    'Total Bonus' => 'โบนัสรวม',
    'Type' => 'ประเภท',
    'TF ESport' => 'TF ESport',
];