<?php
$lang_index = [
    'Affiliate' => 'ร่วมเป็นเอเจ้นท์',
    'Casino' => 'คาสิโน',
    'Cockfight' => 'ไก่ชน',
    'Contact Us' => 'ติดต่อเรา',
    'Fishing' => 'เกมยิงปลา',
    'Forex' => 'ฟอเร็กซ์',
    'Game' => 'เกมส์',
    'Keno' => 'คีโน',
    'Live Casino' => 'คาสิโน',
    'Lottery' => 'ลอตเตอร์รี่',
    'Number' => 'เลข',
    'Poker' => 'โป๊กเกอร์',
    'Promotions' => 'โปรโมชั่น',
    'Slot' => 'สล็อต',
    'Slots' => 'สล็อต',
    'Sports' => 'กีฬา',
    'Login' => 'เข้าสู่ระบบ',
    'Register' => 'ลงทะเบียน',
    'Deposit' => 'เงินฝาก',
    'Transfer' => 'โอนย้าย',
    'Notification' => 'การแจ้งเตือน',
    'Withdraw' => 'ถอน',
    'Announcement' => 'ประกาศ',
];