<?php
$lang = [
    'Account Balance' => 'ยอดเงินในบัญชี',
    'Total Bonus' => 'โบนัสรวม',
    'Last Bonus' => 'โบนัสล่าสุด',
    'Amount' => 'จำนวน',
    'Bonus' => 'โบนัส',
    'Transfer To' => 'โอนไปที่',
    'Transfer From' => 'โอนจาก',
    'Transfer Successfully!' => 'โอนสำเร็จ!',
    'Transfer fail,please transfer again!' => 'โอนไม่สำเร็จ กรุณาโอนใหม่!',
    'Main Balance' => 'ยอดคงเหลือหลัก',
    'Buy In' => 'ซื้อใน',
    'Buy Out' => 'ซื้อออก',
    'Play Now' => 'เล่นเลย',
    'Balance' => 'สมดุล',
    'Please input appropriate amount' => 'กรุณากรอกจำนวนเงินที่เหมาะสม',
    'must be more than 1' => 'ต้องมากกว่า 1',
    'must be more than 5' => 'ต้องมากกว่า 5',
    'transfer failed, Insufficient balance' => 'โอนไม่สำเร็จ ยอดเงินไม่เพียงพอ',
    'transfer failed, please check amount' => 'โอนเงินไม่สำเร็จ กรุณาตรวจสอบจำนวนเงิน',
    'Transfer Amount should be less than' => 'จำนวนเงินที่โอนควรน้อยกว่า',
];