<?php
$lang = [
    'Account Balance' => 'ยอดเงิน',
    'Basic Information' => 'ข้อมูลพื้นฐาน',
    'Bet Reports' => 'รายการเดิมพัน',
    'Bonus' => 'โบนัส',
    'Change Password' => 'เปลี่ยนรหัสผ่าน',
    'Deposit' => 'ฝากเงิน',
    'Last Bonus' => 'โบนัสล่าสุด',
    'Member Center' => 'ศูนย์สมาชิก',
    'Messages' => 'ข้อความ',
    'Referral Lists' => 'รายการอ้างอิง',
    'Statements' => 'รายงานการเงิน',
    'Total Bonus' => 'โบนัสทั้งหมด',
    'Transfer' => 'โอน',
    'Turnover Checking' => 'ผลประกอบการ',
    'Withdrawal' => 'ถอนเงิน',
    'Achievement' => 'ความสำเร็จ',
    'Achievement Report' => 'รายงานความสำเร็จ',
    'Logout' => 'ออกจากระบบ',
    'Referral' => 'การอ้างอิง',
];