<?php
$lang = [
    'Approved' => 'ได้รับการอนุมัติ',
    'Bonus' => 'โบนัส',
    'Bonus List' => 'รายการอ้างอิง',
    'Code' => 'รหัส',
    'End Date' => 'วันที่สิ้นสุด',
    'Finished' => 'เสร็จ',
    'Join Date' => 'เข้าร่วมวันที่',
    'No record found!' => 'ไม่พบบันทึก!',
    'No.' => 'ลำดับ.',
    'Promotion' => 'โปรโมชั่น',
    'Promotion list' => 'รายการส่งเสริมการขาย',
    'Refused' => 'ปฏิเสธ',
    'Session id does not match' => 'เซสชั่นไม่ตรงกับไอดี',
    'Start Date' => 'วันที่เริ่มต้น',
    'Status' => 'สถานะ',
    'Submit' => 'ส่ง',
    'Submitting' => 'กำลังยืนยัน',
    'Turnover' => 'ผลประกอบการ',
    'Update Bonus' => 'อัพเดทโบนัส',
    'close' => 'ปิด',
    'Join Now' => 'เข้าร่วมเดี๋ยวนี้',
    'More' => 'More',
    'Apply For Bonus List' => 'สมัครรายการโบนัส',
];