<?php
$lang = [
    '855 FOREX' => '855 ໂພເຣັກ',
    'Account Balance' => 'ເງິນຄົງເຫຼືອໃນບັນຊີ',
    'Amount' => 'ຈຳນວນ',
    'Bet List' => 'ລາຍການພະນັນ',
    'Bet Records' => 'ບັນທຶກພະນັນ',
    'Bet time' => 'ເວລາພະນັນ',
    'Discount' => 'ສ່ວນຫຼຸດ',
    'Game' => 'ເກມ',
    'Game ID' => 'ລະຫັດເກມ',
    'Last Bonus' => 'ລາງວັນຫຼ້າສຸດ',
    'Member Center' => 'ສູນສະມາຊິກ',
    'No' => 'ບໍ່',
    'No record found!' => 'ບໍ່ມີບັນທຶກຖືກພົບເຫັນ!',
    'Number' => 'ຕົວເລກ',
    'Pool' => 'ພະນັນ',
    'Rate' => 'ອັດຕາ',
    'Sports 2' => 'ກິລາ 2',
    'Total Bonus' => 'ລາງວັນລວມ',
    'Type' => 'ຊະນິດ',
    'TF ESport' => 'TF ESport',
    'Ask service' => 'ຖ້າທ່ານມີຄຳຖາມ ຫຼື ຕ້ອງການສອບຖາມ, ກະລຸນາໃຊ້ສູບໍລິການລູກຄ້າ',
];