<?php
include 'dry.php';

$lang = [
    'Main Balance' => 'ເງິນຄົງເຫຼືອຫຼັກ',
    'Game Balance' => 'ເງິນຄົງເຫຼືອເກມ',
    'Total Bonus' => 'ລາງວັນລວມ',
    'Last Bonus' => 'ລາງວັນຫຼ້າສຸດ',
    'Account Balance' => $account_balance,
    'Amount' => 'ຈຳນວນ',
    'Balance' => 'ເງິນຄົງເຫຼືອ',
    'Buy In' => 'ຊື້ເຂົ້າ',
    'Buy Out' => 'ຊຶ້ອອກ',
    'Play Now' => 'ຫຼີ້ນຕອນນີ້',
    'Game Rules' => 'ກະຕິກາຂອງເກມ',
    'Please input appropriate amount' => 'ກະລຸນາຕື່ມຈຳນວນທີ່ເໝາະສົມເຂົ້າ',
    'Transfer Successfully!' => 'ໂອນສຳເລັດແລ້ວ!',
    'Transfer fail,please transfer again!' => 'ໂອນລົ້ມເຫຼວ,ກະລຸນາໂອນອີກເທື່ອໜຶ່ງ!',
    'Successfully,please try again at 30 second later' => 'ສຳເລັດ,ກະລຸນາລອງອີກເທື່ອໜຶ່ງ 30 ວິນາທີຕາມຫຼັງ',
    'Proccesing,please try again at 30 second later' => 'ກຳລັງດຳເນີນການ,ກະລຸນາລອງອີກເທື່ອໜຶ່ງ 30 ວິນາທີຕາມຫຼັງ',
    'Ongdo' => 'Ongdo',
    'Tienlen' => 'Tienlen',
    'Poke' => 'Poke',
    'Kla Klouk' => 'Kla Klouk',
    'Ham' => 'Ham',
    'Sikuthai' => 'Sikuthai',
    'Kate' => 'Kate',
    'Apoung' => 'Apoung',
    'Kai Yuan' => 'Kai Yuan',
    'Poker' => 'Poker',
    'Close' => 'ປິດ',
];