<?php
include 'dry.php';

$lang = [
    'Account Balance' => $account_balance,
    'Amount' => $amount,
    'Be Closed' => 'ຖືກປິດ',
    'Date' => 'ວັນທີ & ເວລາ',
    'Delete' => 'ລຶບ',
    'Finish' => 'ສຳເລັດ',
    'Fixed bank account' => 'ບັນຊີທະນາຄານຄົງທີ່',
    'For secure property, only supports when mention is bound to registered account.' => $for_secure_property,
    'ID' => 'ລະຫັດ',
    'Last Bonus' => $last_bonus,
    'Member Center' => 'ສູນສະມາຊິກ',
    'No' => 'ເລກທີ',
    'No record found!' => 'ບໍ່ພົບເຫັນບັນທຶກ!',
    'Note' => 'ໝາຍເຫດ',
    'Options' => 'ທາງເລືອກ',
    'Postscript' => 'ຄຳລົງທ້າຍ',
    'Processing' => 'ກຳລັງດຳເນີນການ',
    'Remark' => 'ໝາຍເຫດ',
    'Status' => 'ສະຖານະ',
    'Submitting' => 'ກຳລັງນຳສົ່ງ',
    'Time' => 'ເວລາ',
    'Total Bonus' => $total_bonus,
    'Transaction Id' => 'ລະຫັດປະກອບທຸລະກຳ',
    'Type' => 'ຊະນິດ',
    'Withdraw' => 'ຖອນ',
    'Withdrawal' => 'ຖອນອອກ',
    'Withdrawal List' => 'ລາຍການຖອນອອກ',
];