<?php
include 'dry.php';

$lang = [
    'Account' => 'ບັນຊີ',
    'Account Balance' => $account_balance,
    'All Refs' => 'ລາຍການອ້າງອີງ',
    'Bonus List' => $bonus_list,
    'Basic Information' => 'ຂໍ້ມູນພື້ນຖານ',
    'Date of Birth' => 'ວັນເກີດ',
    'E-mail' => 'ອີເມລ',
    'Full name' => 'ຊື່ເຕັມ',
    'Last Bonus' => $last_bonus,
    'Last Login' => 'ເຂົ້າລະບົບຄັ້ງລ່າສຸດ',
    'Login Name' => 'ຊື່ເຂົ້າລະບົບ',
    'Member Center' => 'ສູນສະມາຊິກ',
    'Phone' => 'ໂທລະສັບ',
    'Ref Link' => 'ເຊື່ອມຕໍ່ການອ້າງອີງ',
    'Referral List' => 'ລາຍການອ້າງອີງ',
    'Register Date' => 'ວັນທີລົງຖະບຽນ',
    'Registration Time' => 'ເວລາລົງທະບຽນ',
    'Total Bonus' => $total_bonus,
    'Withdrawal Account' => 'ບັນຊີສຳລັບການຖອນ',
    'Withdrawal Bank' => 'ທະນາຄານໃນການຖອນ',
    'Withdrawal No.' => 'ຕົວເລກທະນາຄານໃນການຖອນ',
    'Account Information' => 'ຂໍ້ມູນບັນຊີ',
    'Account Name' => 'ຊື່ບັນຊີ',
    'Address' => 'ທີ່ຢູ່',
    'Bank Account Name' => $bank_account_name,
    'Bank Account Number' => $bank_account_number,
    'Bank Name' => $bank_name,
    'Contact Number' => 'ເບີຕິດຕໍ່',
    'Currency' => 'ສະກຸນເງິນ',
    'Female' => 'ເພດຍິງ',
    'Gender' => 'ເພດ',
    'Male' => 'ເພດຊາຍ',
    'Personal Information' => 'ຂໍ້ມູນສ່ວນຕົວ',
    'Copy' => 'ສຳເນົາ',
];