<?php
$lang = [
    'Approved' => 'ໄດ້ຮັບການອະນຸມັດແລ້ວ',
    'Bonus' => 'ຂອງລາງວັນ',
    'Bonus List' => 'ລາຍການ ຂອງລາງວັນ',
    'Code' => 'ລະຫັດ',
    'End Date' => 'ວັນເດືອນປີສີ້ນສຸດ',
    'Finished' => 'ສຳເລັດແລ້ວ',
    'Join Date' => 'ວັນເດືອນປີເຂົ້າຮ່ວມ',
    'No record found!' => 'ບໍ່ພົບບັນທຶກ!',
    'No.' => 'ລຳດັບ.',
    'Promotion' => 'ໂປຣໂມຊັນ',
    'Promotion list' => 'ລາຍການໂປຣໂມຊັນ',
    'Refused' => 'ຖືກປະຕິເສດ',
    'Session id does not match' => 'ລະຫັດເຂົ້າຮ່ວມບໍຕົງກັນ',
    'Start Date' => 'ວັນເດືອນປີເລີ່ມຕົ້ນ',
    'Status' => 'ສະຖານະ',
    'Submit' => 'ນຳສົ່ງ',
    'Submitting' => 'ກຳລັງນຳສົ່ງ',
    'Turnover' => 'ຜົນຕອບຮັບ',
    'Update Bonus' => 'ອັບເດດຂອງລາງວັນ',
    'close' => 'ປິດ',
    'Join Now' => 'ເຂົ້າຮວ່ມຕອນນີ້',
    'More' => 'ເພີ່ມເຕິມ',
    'Apply For Bonus List' => 'ຮ້ອງຂໍເອົາລາຍການຂອງລາງວັນ',
];