<?php
$lang = [
    'Approved' => 'ຮັບອະນຸມັດ',
    'Bonus' => 'ລາງວັນ',
    'Bonus List' => 'ລາຍການອ້າງອີງ',
    'Code' => 'ລະຫັດ',
    'End Date' => 'ວັນເດືອນປີສີ້ນສຸດ',
    'Finished' => 'ສຳເລັດແລ້ວ',
    'Join Date' => 'ວັນເດືອນປີເຂົ້າຮ່ວມ',
    'No record found!' => 'ບໍ່ພົບບັນທຶກ!',
    'No.' => 'ບໍ່.',
    'Promotion' => 'ໂປຣໂມຊັນ',
    'Promotion list' => 'ລາຍການໂປຣໂມຊັນ',
    'Refused' => 'ຖືກປະຕິເສດ',
    'Session id does not match' => 'ລະຫັດຊ່ວງບໍ່ເຂົ້າກັນ',
    'Start Date' => 'ວັນເດືອນປີເລີ່ມຕົ້ນ',
    'Status' => 'ສະຖານະ',
    'Submit' => 'ສົ່ງ',
    'Submitting' => 'ກຳລັງສົ່ງ',
    'Turnover' => 'ຜົນຕອບແທນ',
    'Update Bonus' => 'ອັບເດດລາງວັນ',
    'close' => 'ປິດ',
    'Join Now' => 'ເຂົ້າຮວ່ມຕອນນີ້',
    'More' => 'ຫຼາຍກວ່າ',
    'Apply For Bonus List' => 'ຂໍລາຍການລາງວັນ',
];